services:
  app:
    image: node:18
    container_name: node_app
    restart: always
    working_dir: /usr/src/app
    env_file:
      - /home/elleo/app/.env
    environment:
      NODE_ENV: production
    volumes:
      - /home/elleo/app:/usr/src/app
    command: bash -c "npm install && npm run discord"
